# ESPHome secrets
wifi_ssid: "<WiFi-SSID>"
wifi_password: "<WiFi-password>"
ap_wifi_password: "<AP-WiFi-password>*"
otapw: "<OTA-password>"
web_username: "<Web-username>"
web_password: "<Web-password>*"
api_key: "<API-key>"
