wifi_ssid: "Your_WiFi_SSID"
wifi_password: "Your_WiFi_Password"
ap_wifi_password: "Your_AP_WiFi_Password"
otapw: "Your_OTA_Password"
web_username: "Your_Web_Username"
web_password: "Your_Web_Password"
api_key: "Your_API_Key"
